### ISSUE TITLE
Databus Storage

### ISSUE THREAD

**Issue by jods4** [rebus-org/Rebus.Oracle#11]
Feature request: please add a Databus Storage to Rebus.Oracle? 

I guess it could work in a similar way to SQL Server, adapted to PL/SQL.

**Comment by jods4** [comment]
FYI I started working on this.
I used SQL Server as a reference implementation (+ copied the tests over).

It's mostly done but there are a few tricky bits that I need to fix with an actual Oracle DB.

@mookid8000 SQL Server implementation does `TOP 1` on its queries by `id`, is there a reason for that? Strangely, `id` is not defined as a primary key.

What are the specification for the `id` of a data bus item? Can you ever get duplicates?

**Comment by mookid8000** [comment]
> SQL Server implementation does TOP 1 on its queries by id, is there a reason for that? Strangely, id is not defined as a primary key.

That's weird – and no, I can't think of any reason why. The Id should be PK.

> What are the specification for the id of a data bus item? Can you ever get duplicates?

No, that should not be possible.
